<?php

// Create 'config/production.php' and use APP_ENV=production environment
// variable to override this default config.

return [
    'base_uri' => 'http://localhost:3000',
    'slim' => [
        'displayErrorDetails' => true,
        'renderer' => [
            'template_path' => __BASE__ . '/src/templates/',
        ],
    ],
    'auth' => [
        // '<username>' => '<password_hash>'
        // When using in production, override these with credentials of your
        // choice. Don't use plaintext passwords!
        // These are default credentials.
        'users' => [
            'admin' => password_hash('notsosecure', PASSWORD_BCRYPT),
        ],
        'routes' => [
            '/show/all',
        ],
    ],
    'ip' => [
        // You can use Cisco style IP ranges to block multiple IPs
        // e.g. '192.168.0.0/24'
        'whitelist' => [],
        'blacklist' => [],
    ],
    'paste' => [
        // paste uid length
        'uid_length' => 7,
        // default syntax
        'syntax_default' => 'plain',
        // syntax mapping and their aliases
        'syntax_list' => [
            'plain'         => ['plaintext'],
            '1с'            => ['1с'],
            'accesslog'     => ['accesslog'],
            'actionscript'  => ['actionscript'],
            'apache'        => ['apache'],
            'applescript'   => ['applescript'],
            'arduino'       => ['arduino'],
            'armasm'        => ['arm-asm'],
            'asciidoc'      => ['asciidoc'],
            'asciidoc'      => ['asciidoc'],
            'aspectj'       => ['aspectj'],
            'autohotkey'    => ['autohotkey'],
            'autoit'        => ['autoit'],
            'avrasm'        => ['avr-asm'],
            'axapta'        => ['axapta'],
            'bash'          => ['bash'],
            'basic'         => ['basic', 'quickbasic'],
            'bat'           => ['bat'],
            'brainfuck'     => ['brainfuck'],
            'c'             => ['c', 'angelscript'],
            'cal'           => ['c/al'],
            'capnproto'     => ['cap\'n-proto'],
            'ceylon'        => ['ceylon'],
            'clojure'       => ['clojure'],
            'clojure-repl'  => ['clojure-repl'],
            'cmake'         => ['cmake'],
            'coffeescript'  => ['coffeescript'],
            'cos'           => ['caché-script', 'cos'],
            'cpp'           => ['c++'],
            'crmsh'         => ['crmsh'],
            'crystal'       => ['crystal'],
            'csharp'        => ['c#', 'csharp'],
            'csp'           => ['csp'],
            'css'           => ['css'],
            'd'             => ['d'],
            'dart'          => ['dart'],
            'delphi'        => ['delphi', 'pascal', 'freepascal'],
            'diff'          => ['diff'],
            'django'        => ['django'],
            'dns'           => ['dns-zone', 'dig'],
            'dockerfile'    => ['dockerfile'],
            'dos'           => ['dos-bat'],
            'dts'           => ['device-tree', 'dts'],
            'dust'          => ['dust'],
            'elixir'        => ['elixir'],
            'elm'           => ['elm'],
            'erb'           => ['erb'],
            'erlang'        => ['erlang'],
            'erlang-repl'   => ['erlang-repl'],
            'fix'           => ['fix'],
            'fortran'       => ['fortran'],
            'fsharp'        => ['f#', 'fsharp'],
            'gams'          => ['gams'],
            'gauss'         => ['gauss'],
            'gcode'         => ['gcode'],
            'gherkin'       => ['gherkin'],
            'glsl'          => ['glsl'],
            'go'            => ['go'],
            'golo'          => ['golo'],
            'gradle'        => ['gradle'],
            'groovy'        => ['groovy'],
            'haml'          => ['haml'],
            'handlebars'    => ['handlebars'],
            'haskell'       => ['haskell'],
            'haxe'          => ['haxe'],
            'hsp'           => ['hsp'],
            'html'          => ['html'],
            'htmlbars'      => ['htmlbars'],
            'http'          => ['http'],
            'inform7'       => ['inform7'],
            'ini'           => ['ini', 'toml'],
            'irpf90'        => ['irpf90'],
            'java'          => ['java'],
            'javascript'    => ['js', 'javascript', 'es', 'ecmascript'],
            'json'          => ['json'],
            'julia'         => ['julia'],
            'kotlin'        => ['kotlin'],
            'lasso'         => ['lasso'],
            'less'          => ['less'],
            'lisp'          => ['lisp', 'commonlisp'],
            'livecode'      => ['livecode'],
            'livescript'    => ['livescript'],
            'lua'           => ['lua'],
            'makefile'      => ['makefile'],
            'markdown'      => ['markdown', 'md'],
            'mathematica'   => ['mathematica'],
            'matlab'        => ['matlab'],
            'maxima'        => ['maxima'],
            'mel'           => ['mel'],
            'mercury'       => ['mercury'],
            'mipsasm'       => ['mips-asm'],
            'mizar'         => ['mizar'],
            'mojolicious'   => ['mojolicious'],
            'monkey'        => ['monkey'],
            'moonscript'    => ['moonscript'],
            'nginx'         => ['nginx'],
            'nimrod'        => ['nimrod'],
            'nix'           => ['nix'],
            'nsis'          => ['nsis'],
            'objectivec'    => ['objective-c'],
            'ocaml'         => ['ocaml'],
            'openscad'      => ['openscad'],
            'oxygene'       => ['oxygene'],
            'parser3'       => ['parser3'],
            'perl'          => ['perl'],
            'pf'            => ['pf'],
            'php'           => ['php'],
            'powershell'    => ['powershell'],
            'processing'    => ['processing'],
            'profile'       => ['python-profile'],
            'prolog'        => ['prolog'],
            'protobuf'      => ['protobuf'],
            'puppet'        => ['puppet'],
            'python'        => ['python'],
            'q'             => ['q'],
            'qml'           => ['qml'],
            'r'             => ['r'],
            'rib'           => ['rib', 'renderman-rib'],
            'roboconf'      => ['roboconf'],
            'rsl'           => ['rsl', 'renderman-rsl'],
            'ruby'          => ['ruby'],
            'rules'         => ['rules', 'oracle-rules'],
            'rust'          => ['rust'],
            'scala'         => ['scala'],
            'scheme'        => ['scheme'],
            'scilab'        => ['scilab'],
            'scss'          => ['scss', 'sass'],
            'sh'            => ['sh'],
            'smali'         => ['smali'],
            'smalltalk'     => ['smalltalk'],
            'sml'           => ['sml'],
            'sqf'           => ['sqf'],
            'sql'           => ['sql'],
            'stan'          => ['stan'],
            'stata'         => ['stata'],
            'step21'        => ['step21'],
            'stylus'        => ['stylus'],
            'swift'         => ['swift'],
            'taggerscript'  => ['taggerscript'],
            'tcl'           => ['tcl'],
            'tp'            => ['tp'],
            'tex'           => ['tex', 'latex'],
            'thrift'        => ['thrift'],
            'twig'          => ['twig'],
            'typescript'    => ['typescript', 'ts'],
            'vala'          => ['vala'],
            'vbnet'         => ['vbnet'],
            'vbscript'      => ['vbscript'],
            'vbscript-html' => ['vbscript-html'],
            'verilog'       => ['verilog'],
            'vim'           => ['vim-script'],
            'vhdl'          => ['vhdl'],
            'x86asm'        => ['x86-asm', 'intel-x86-asm', 'asm'],
            'xml'           => ['xml'],
            'xl'            => ['xl'],
            'xquery'        => ['xquery'],
            'yaml'          => ['yaml'],
            'zephir'        => ['zephir'],
        ],
    ],
];
